#!/usr/bin/bash
a=1;x=1
while getopts "axAX" o; do
	case $o in
		a) a=0 ;;
		x) x=0 ;;
		A) a=1 ;;
		X) x=1 ;;
	esac
done
for ((i=1;i<OPTIND;i++)); do shift; done
if ((a>0)); then pre="$pre:.al"; fi
if ((x>0)); then pre="$pre:.xl"; fi
ifile="${1:-/dev/stdin}"
ofile="${2:-/dev/stdout}"
cat <(echo $pre) "$ifile" | while read line; do
	re='\b(sep|rep) +#(\$)?([0-9a-fA-F]+)'
	printf "%s" "$line"
	if [[ $line =~ $re ]]; then
		op=${BASH_REMATCH[1]}
		v=${BASH_REMATCH[3]}
		if [[ ${BASH_REMATCH[2]} == '$' ]]; then v=0x$v; fi
		case $op in
			sep)
				if (($v & 0x20)); then printf " :.as"; fi
				if (($v & 0x10)); then printf " :.xs"; fi ;;
			rep)
				if (($v & 0x20)); then printf " :.al"; fi
				if (($v & 0x10)); then printf " :.xl"; fi ;;
		esac
	fi
	printf "\n"
done | xa -w -o "$ofile" /dev/stdin
